[package]
name = "string-sum"
version = "0.1.0"
edition = "2018"

[lib]
name = "string_sum"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.9.0"
ndarray = "0.13"
ndarray-stats = "0.3.0"
numpy = "0.8.0"
num = "0.2.1"

[dependencies.pyo3]
version = "0.11.1"
features = ["extension-module"]
